/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
import java.awt.EventQueue;
import java.sql.*;
import java.util.*;
import javax.swing.*;
public class Functions extends javax.swing.JFrame {

  
//   public void run (){
//   try {
//      Functions fn=new Functions();
//      fn.setVisible(true);
//   } catch (Exception e){
//        e.printStackTrace();
//       }
//   }
   
    
    
    
    /**
     * Creates new form Functions
     */
    public Functions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        AddOperator = new javax.swing.JButton();
        update = new javax.swing.JButton();
        deleteop = new javax.swing.JButton();
        deletesp = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        viewts = new javax.swing.JButton();
        viewreport = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("cost for an hour");

        jScrollPane1.setViewportView(jTextPane1);

        AddOperator.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AddOperator.setForeground(new java.awt.Color(0, 102, 153));
        AddOperator.setText("add operator");
        AddOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOperatorActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        update.setForeground(new java.awt.Color(0, 102, 153));
        update.setText("update operator");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        deleteop.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deleteop.setForeground(new java.awt.Color(0, 102, 153));
        deleteop.setText("delete operator");
        deleteop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteopActionPerformed(evt);
            }
        });

        deletesp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deletesp.setForeground(new java.awt.Color(0, 102, 153));
        deletesp.setText("delete spot");
        deletesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletespActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 0, 0));
        jButton6.setText("log out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        viewts.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        viewts.setForeground(new java.awt.Color(0, 102, 153));
        viewts.setText("view total spots");
        viewts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewtsActionPerformed(evt);
            }
        });

        viewreport.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        viewreport.setForeground(new java.awt.Color(0, 102, 153));
        viewreport.setText("view report");
        viewreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewreportActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("View Operators Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddOperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deletesp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(viewts, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(viewreport, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(AddOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(deleteop, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deletesp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewts, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewreport, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure to logout? ", "Concirmation Message",JOptionPane.YES_NO_OPTION);
        if(choice == 0){
            this.dispose();
        }     
    }                                         

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","");
            String sql="Select * from Customer where user=? and =pas=?";
             PreparedStatement pSt=con.prepareStatement(sql);
             pSt.setString(1,update.getText());
             
             ResultSet rs=pSt.executeQuery();
             if( rs.next())
            {
                
             JOptionPane.showMessageDialog(null,"Username and password Matched");
             
              
           }
                     
             else
             {
                 JOptionPane.showMessageDialog(null,"Username and password  Not Matched");
                 update.setText("");
                
             }
         con.close();
             
             
            

        }
        catch(Exception e)
        {
           JOptionPane .showMessageDialog(null,e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void AddOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOperatorActionPerformed
        // TODO add your handling code here:
       try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","");
            String sql="Select * from Customer where user=? and =pas=?";
             PreparedStatement pSt=con.prepareStatement(sql);
             pSt.setString(1,AddOperator.getText());
     
             ResultSet rs=pSt.executeQuery();
             if( rs.next())
            {
                
             JOptionPane.showMessageDialog(null,"Username and password Matched");
             
              
           }
                     
             else
             {
                 JOptionPane.showMessageDialog(null,"Username and password  Not Matched");
                 AddOperator.setText("");
                 
             }
         con.close();
             
             
            AddOperator ao = new AddOperator();
            ao.show();

        }
        catch(Exception e)
        {
           JOptionPane .showMessageDialog(null,e);
        }
    }//GEN-LAST:event_AddOperatorActionPerformed

    private void deleteopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteopActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","");
            String sql="Select * from Customer where user=? and =pas=?";
             PreparedStatement pSt=con.prepareStatement(sql);
             pSt.setString(1,deleteop.getText());
             
             ResultSet rs=pSt.executeQuery();
             if( rs.next())
            {
                
             JOptionPane.showMessageDialog(null,"Username and password Matched");
             
              
           }
                     
             else
             {
                 JOptionPane.showMessageDialog(null,"Username and password  Not Matched");
                 deleteop.setText("");
                 
             }
         con.close();
             
             
            

        }
        catch(Exception e)
        {
           JOptionPane .showMessageDialog(null,e);
        }
    }//GEN-LAST:event_deleteopActionPerformed

    private void deletespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletespActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","");
            String sql="Select * from Customer where user=? and =pas=?";
             PreparedStatement pSt=con.prepareStatement(sql);
             pSt.setString(1,deletesp.getText());
             
             ResultSet rs=pSt.executeQuery();
             if( rs.next())
            {
                
             JOptionPane.showMessageDialog(null,"Username and password Matched");
             
              
           }
                     
             else
             {
                 JOptionPane.showMessageDialog(null,"Username and password  Not Matched");
                 deletesp.setText("");
                 
             }
         con.close();
             
             
            

        }
        catch(Exception e)
        {
           JOptionPane .showMessageDialog(null,e);
        }
    }//GEN-LAST:event_deletespActionPerformed

    private void viewtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewtsActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","");
            String sql="Select * from Customer where user=? and =pas=?";
             PreparedStatement pSt=con.prepareStatement(sql);
             pSt.setString(1,viewts.getText());
             
             ResultSet rs=pSt.executeQuery();
             if( rs.next())
            {
                
             JOptionPane.showMessageDialog(null,"Username and password Matched");
             
              
           }
                     
             else
             {
                 JOptionPane.showMessageDialog(null,"Username and password  Not Matched");
                 viewts.setText("");
                 
             }
         con.close();
             
             
            

        }
        catch(Exception e)
        {
           JOptionPane .showMessageDialog(null,e);
        }
    }//GEN-LAST:event_viewtsActionPerformed

    private void viewreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewreportActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","");
            String sql="Select * from Customer where user=? and =pas=?";
             PreparedStatement pSt=con.prepareStatement(sql);
             pSt.setString(1,viewreport.getText());
             
             ResultSet rs=pSt.executeQuery();
             if( rs.next())
            {
                
             JOptionPane.showMessageDialog(null,"Username and password Matched");
             
              
           }
                     
             else
             {
                 JOptionPane.showMessageDialog(null,"Username and password  Not Matched");
                 viewreport.setText("");
                 
             }
         con.close();
             
             
            

        }
        catch(Exception e)
        {
           JOptionPane .showMessageDialog(null,e);
        }
    }//GEN-LAST:event_viewreportActionPerformed

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOperator;
    private javax.swing.JButton deleteop;
    private javax.swing.JButton deletesp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton update;
    private javax.swing.JButton viewreport;
    private javax.swing.JButton viewts;
    // End of variables declaration//GEN-END:variables

    
}
